# Site settings
title: Lacuna Lab
email: info@lacunalab.org
description: > # this means to ignore newlines until "baseurl:"
  Collaborative co-creation space in Berlin Kreuzberg.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lacunalab.com" # the base hostname & protocol for your site
twitter_username: LacunaLab
github_username:  LacunaLab

# Build settings
markdown: kramdown
future: true

collections:
  events:
    output: true